### PR TITLE
Add Windows Support

### PR DESCRIPTION
**Pull request by davidcorrigan714**
Follow up to my [bonjour-sys PR](https://github.com/windy1/bonjour-sys/pull/3) for windows support. Might as well get both going to address any feedback.

Mostly the code needed some tweaks here and there for windows specific socket calls and it seems to work fine otherwise. The service & browser examples run. It's a bit odd that there's now windows code in the macos folder but also seemed like a good chunk of refactoring or renaming to clean that up though it could be done. I haven't done any thorough testing beyond that but will probably set this branch as a git dependency on  the personal project I want this for and kick the tires a bit more this week across all 3 platforms.

### CODE REVIEW

**Comment by windy1** [comment]
Hey there!  👋 

Thanks so much for submitting this. The changes looks good to me. I'm away this weekend and don't have access to a Windows machine right now so before I merge I would just like to verify the changes myself.

I agree the directory naming is weird; I was planning on renaming them to `bonjour` and `avahi` instead when I eventually got around to Windows support. If you would like to include those changes in this PR or create a subsequent PR I would be happy to accept. I think I would likely want to rename these directories before another release goes out anyways.

**Comment by piense** [comment]
Missed that there's a workflow for this too, I'll add windows to that too.

**Comment by davidcorrigan714** [comment]
Missed that there's a workflow for this too, I'll add windows to that too.

**Comment by davidcorrigan714** [comment]
Updated for the folder renames, windows builds, & some clippy updates.

**Comment by davidcorrigan714** [comment]
Looks like the lock file is a bit off from building against my branch but that's not really fixable until the update to bonjour-sys is in.

**Review by windy1 — APPROVED** [review]

**Pull request closed without merging**
