### PR TITLE
Replace `target_os = "macos"` with `target_vendor = "apple"`

### PR DESCRIPTION
**Pull request by aspenluxxxy**
Title. Otherwise it fails to compile on iOS and friends.

### CODE REVIEW

**Comment by windy1** [comment]
Thanks for your contribution! Could you please share what target(s) you used to test this? I would assume that Bonjour would be present for all apple targets but I'm not sure tbh.

**Comment by aspenluxxxy** [comment]
Tested on `aarch64-apple-ios`, it compiles but I'm not sure it 100% works.

**Comment by windy1** [comment]
Okay yeah I think we need to better than that. This assumes that the Bonjour lib is exactly the same on iOS, I suspect it is but I'd like to have a bit more certainty before I would pull this.

**Comment by aspenluxxxy** [comment]
Yeah - I'm not entirely sure if the problem is zeroconf-rs or my own configuration / testing setup

I'll figure it out

**Comment by aspenluxxxy** [comment]
Update: it works, I was just testing it wrong.

I got a Bonjour browser app on my iPhone, then launched the `zeroconf-rs` test on my iPhone through SSH, and it immediately showed up.

**Comment by windy1** [comment]
Excellent! Thank you for confirming. That's great, this crate probably has more use-cases on mobile than any other platform. I'm going to take your word for it that it's working because I'm too busy (lazy) to set up an iOS testing env lmao but I've confirmed that it still compiles on macOS.

**Comment by windy1** [comment]
I've published this rev to 0.7.1, cheers!

**Pull request merged**
